#!/usr/bin/env bash
# A script to install nginx server.
# Update and restart

sudo apt-get update

# Install nginx.
sudo apt-get install -y nginx

# Default index.html.
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
     listen      80;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

# Restart nginx.
service nginx restart
