#!/usr/bin/env bash
# A script to install nginx server.
# Update and restart

sudo apt-get update

# Install nginx.
sudo apt-get install -y nginx

# Default index.html.
sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo service nginx start
