#!/usr/bin/env bash
# load balancer configurations

apt-get -y update
apt-get -y install haproxy=1.6.\*

echo '
frontend sammykingx.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 452159-web-01 34.203.29.245:80
        server 452159-web-02 54.88.114.244:80
' >> /etc/haproxy/haproxy.cfg

# Restart
service haproxy restart
